# XMB Item Hider ini file
# 0 = NO | 1 = YES | 2 = Hide entire category ("Global" entries only)

# If you hide categories using "2", you must hide at least two categories
# unless the only category you hide is "PlayStation®Network" ("HIDE_ALL_PSN = 2").
# It's recommended to limit the use of "2" to "HIDE_ALL_NETWORK" and "HIDE_ALL_PSN"-
# there are bugs when the "Game" category gets shifted to the left. 
# However, you *can* safely hide the "Extras" category by applying one of the following
# VSH regions in CFW settings: Latin America|Hong Kong|Taiwan|Russia|China|Debug I

[Global]
USE_PLUGIN = 1
MOVE_ARK_EXTRAS = 0
START_AT_MEMORY_STICK = 0
HIDE_ALL = 0
HIDE_ALL_SETTINGS = 0
HIDE_ALL_EXTRAS = 0
HIDE_ALL_PHOTO = 0
HIDE_ALL_MUSIC = 0
HIDE_ALL_VIDEO = 0
HIDE_ALL_GAME = 0
HIDE_ALL_NETWORK = 0
HIDE_ALL_PSN = 0

# 0 = SHOW | 1 = HIDE

[Settings]
SYSTEM_UPDATE = 0
USB = 0
VIDEO = 0
PHOTO = 0
SYSTEM = 0
THEME = 0
DATE = 0
POWERSAVE = 0
BLUETOOTH = 0
DISPLAY = 0
SOUND = 0
SECURITY = 0
RSS = 0
NETWORK = 0

[Extras]
1SEG = 0
T-DMB = 0
JP_BOOKREADER = 0
DIGITAL_COMICS = 0
X-RADAR_PORTABLE = 0

[Photo]
CAMERA = 0
MEMORY_STICK = 0
SYSTEM_STORAGE = 0

[Music]
MUSIC_UNLIMITED = 0
SENSME_CHANNELS = 0
MEMORY_STICK = 0
SYSTEM_STORAGE = 0

[Video]
MEMORY_STICK = 0
SYSTEM_STORAGE = 0

[Game]
GAME_SHARING = 0
UMD_UPDATE = 0
SAVED_DATA_UTILITY_MS = 0
SAVED_DATA_UTILITY_EF = 0
RESUME_GAME = 0
MEMORY_STICK = 0
SYSTEM_STORAGE = 0

[Network]
ONLINE_MANUAL = 0
LOCATION_FREE_PLAYER = 0
SKYPE = 0
REMOTE_PLAY = 0
INTERNET_RADIO = 0
RSS_CHANNEL = 0
INTERNET_BROWSER = 0
INTERNET_SEARCH = 0
PLAYSTATION_SPOT = 0
GO_MESSENGER = 0

[PlayStation®Network]
SIGN_UP_OR_ACCOUNT_MANAGEMENT = 0
PLAYSTATION_STORE = 0
INFORMATION_BOARD = 0